language: node_js
node_js:
  - "4.2"
  - "0.12"
  - "0.11"
  - "0.10"
before_install:
  - npm install -g mocha grunt grunt-cli codeclimate-test-reporter
  - npm install
  - grunt build
  - grunt build-test
script:
  - grunt test
after_script:
  - codeclimate-test-reporter < test/coverage/reports/lcov.info
notifications:
  email: false
sudo: false
addons:
  code_climate:
    repo_token: 8162971467592a99338544cf9049d13739cbff25a0dece1f7ee80941f1f89491